# development: docker-compose up
# production: NODE_ENV=production docker-compose up -d

version: '3'
services:
  web:
    build:
      context: .
      target: ${NODE_ENV:-development}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    command: npm run ${NODE_ENV:-development}